<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Python Tutorial: 9. Error Handling | Tiexin Guo</title><meta name=keywords content="python"><meta name=description content="We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I&rsquo;m pretty sure you&rsquo;ve met a few more errors and exceptions. Today, we will go over errors in general. There are (at least) two distinguishable kinds of errors: syntax errors exceptions 1 Syntax Errors Syntax errors, also known as parsing errors, are caused by incorrect syntax, or grammar. They are perhaps the"><meta name=author content="Tiexin Guo | 郭铁心"><link rel=canonical href=https://www.guotiexin.com/posts/python-09-error-handling/><link crossorigin=anonymous href=/assets/css/stylesheet.bc1149f4a72aa4858d3a9f71462f75e5884ffe8073ea9d6d5761d5663d651e20.css integrity="sha256-vBFJ9KcqpIWNOp9xRi915YhP/oBz6p1tV2HVZj1lHiA=" rel="preload stylesheet" as=style><script defer crossorigin=anonymous src=/assets/js/highlight.f413e19d0714851f6474e7ee9632408e58ac146fbdbe62747134bea2fa3415e0.js integrity="sha256-9BPhnQcUhR9kdOfuljJAjlisFG+9vmJ0cTS+ovo0FeA=" onload=hljs.initHighlightingOnLoad()></script>
<link rel=icon href=https://www.guotiexin.com/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://www.guotiexin.com/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://www.guotiexin.com/favicon-32x32.png><link rel=apple-touch-icon href=https://www.guotiexin.com/apple-touch-icon.png><link rel=mask-icon href=https://www.guotiexin.com/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:title" content="Python Tutorial: 9. Error Handling"><meta property="og:description" content="We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I&rsquo;m pretty sure you&rsquo;ve met a few more errors and exceptions. Today, we will go over errors in general. There are (at least) two distinguishable kinds of errors: syntax errors exceptions 1 Syntax Errors Syntax errors, also known as parsing errors, are caused by incorrect syntax, or grammar. They are perhaps the"><meta property="og:type" content="article"><meta property="og:url" content="https://www.guotiexin.com/posts/python-09-error-handling/"><meta property="og:image" content="https://www.guotiexin.com/1200px-Python-logo.png"><meta property="article:section" content="posts"><meta property="article:published_time" content="2022-07-19T00:00:00+00:00"><meta property="article:modified_time" content="2022-07-19T00:00:00+00:00"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="https://www.guotiexin.com/1200px-Python-logo.png"><meta name=twitter:title content="Python Tutorial: 9. Error Handling"><meta name=twitter:description content="We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I&rsquo;m pretty sure you&rsquo;ve met a few more errors and exceptions. Today, we will go over errors in general. There are (at least) two distinguishable kinds of errors: syntax errors exceptions 1 Syntax Errors Syntax errors, also known as parsing errors, are caused by incorrect syntax, or grammar. They are perhaps the"><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":2,"name":"Posts","item":"https://www.guotiexin.com/posts/"},{"@type":"ListItem","position":3,"name":"Python Tutorial: 9. Error Handling","item":"https://www.guotiexin.com/posts/python-09-error-handling/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Python Tutorial: 9. Error Handling","name":"Python Tutorial: 9. Error Handling","description":"We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I\u0026rsquo;m pretty sure you\u0026rsquo;ve met a few more errors and exceptions. Today, we will go over errors in general. There are (at least) two distinguishable kinds of errors: syntax errors exceptions 1 Syntax Errors Syntax errors, also known as parsing errors, are caused by incorrect syntax, or grammar. They are perhaps the","keywords":["python"],"articleBody":"We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I’m pretty sure you’ve met a few more errors and exceptions. Today, we will go over errors in general.\nThere are (at least) two distinguishable kinds of errors:\nsyntax errors exceptions 1 Syntax Errors Syntax errors, also known as parsing errors, are caused by incorrect syntax, or grammar.\nThey are perhaps the most common kind of complaints you get while you are learning Python:\n\u003e\u003e\u003e while True print('Hello world') File \"\", line 1 while True print('Hello world') ^ SyntaxError: invalid syntax The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected.\nThe error is caused by (or at least detected at) the token preceding the arrow. In the example above, the error is detected at the function print(), since a colon (:) is missing before it.\nFile name and line number are printed so you know where to look in case the input came from a script. It’s extremely important to learn to figure out where went wrong and why, because that’s all you do when programming.\n2 Exceptions Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it.\nErrors detected during execution are called exceptions and are not always “fatal” in every condition. You will soon learn how to handle exceptions in Python.\nMost exceptions are not handled by programs, however, and result in error messages as shown here:\n\u003e\u003e\u003e 1/0 Traceback (most recent call last): File \"\", line 1, in \u003cmodule\u003e ZeroDivisionError: division by zero \u003e\u003e\u003e 4 + spam*3 Traceback (most recent call last): File \"\", line 1, in \u003cmodule\u003e NameError: name 'spam' is not defined \u003e\u003e\u003e '2' + 2 Traceback (most recent call last): File \"\", line 1, in \u003cmodule\u003e TypeError: can only concatenate str (not \"int\") to str The last line of the error message indicates what happened.\nExceptions come in different types, and the type is printed as part of the message.\nThe types in the example are ZeroDivisionError, NameError, and TypeError.\nThe rest of the line provides detail based on the type of exception and what caused it.\n3 Handling Exceptions It is possible to write programs that handle selected exceptions.\nRead the following example, which asks the user for input until a valid integer has been entered, but allows the user to interrupt the program (using Control-C or whatever the operating system supports.)\nNote that a user-generated interruption is signaled by raising the KeyboardInterrupt exception:\n\u003e\u003e\u003e while True: ... try: ... x = int(input(\"Please enter a number: \")) ... break ... except ValueError: ... print(\"Oops! That was no valid number. Try again...\") ... The try statement works as follows:\nThe try clause (the statement(s) between the try and except keywords) is executed. If no exception occurs, the except clause is skipped and execution of the try statement are finished. If an exception occurs during the execution of the try clause, the rest of the clause is skipped. Then, if the exception’s type matches the exception named after the except keyword, the except clause is executed, and then execution continues after the try/except block. If an exception occurs that does not match the exception named in the except clause, it is passed on to outer try statements (if there is); if no outer try handler is found, it is an unhandled exception, and execution stops. It’s worth noting that a try statement may have more than one except clause, to specify handlers for different exceptions. At most one handler will be executed. Handlers only handle exceptions that occur in the corresponding try clause, not in other handlers of the same try statement.\nAn except clause may name multiple exceptions as a parenthesized tuple, for example:\n... except (RuntimeError, TypeError, NameError): ... pass The try … except statement has an optional else clause, which, when present, must follow all except clauses. It is useful for code that must be executed if the try clause does not raise an exception. For example:\nfor arg in sys.argv[1:]: try: f = open(arg, 'r') except OSError: print('cannot open', arg) else: print(arg, 'has', len(f.readlines()), 'lines') f.close() The use of the else clause is better than adding additional code to the try clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the try … except statement.\nException handlers don’t just handle exceptions if they occur immediately in the try clause, but also if they occur inside functions that are called (even indirectly) in the try clause. For example:\n\u003e\u003e\u003e def this_fails(): ... x = 1/0 ... \u003e\u003e\u003e try: ... this_fails() ... except ZeroDivisionError as err: ... print('Handling run-time error:', err) ... Handling run-time error: division by zero 4 Raising Exceptions The raise statement allows the programmer to force a specified exception to occur. For example:\n\u003e\u003e\u003e raise NameError('HiThere') Traceback (most recent call last): File \"\", line 1, in \u003cmodule\u003e NameError: HiThere The sole argument to raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from Exception). If an exception class is passed, it will be implicitly instantiated by calling its constructor with no arguments:\nraise ValueError # shorthand for 'raise ValueError()' If you need to determine whether an exception was raised but don’t intend to handle it, a simpler form of the raise statement allows you to re-raise the exception:\n\u003e\u003e\u003e try: ... raise NameError('HiThere') ... except NameError: ... print('An exception flew by!') ... raise ... An exception flew by! Traceback (most recent call last): File \"\", line 2, in \u003cmodule\u003e NameError: HiThere 5 Exception Chaining The raise statement allows an optional form that enables chaining exceptions. Syntax:\n# exc must be exception instance or None. raise RuntimeError from exc This can be useful when you are transforming exceptions. Example:\n\u003e\u003e\u003e def func(): ... raise ConnectionError ... \u003e\u003e\u003e try: ... func() ... except ConnectionError as exc: ... raise RuntimeError('Failed to open database') from exc ... Traceback (most recent call last): File \"\", line 2, in \u003cmodule\u003e File \"\", line 2, in func ConnectionError The above exception was the direct cause of the following exception: Traceback (most recent call last): File \"\", line 4, in \u003cmodule\u003e RuntimeError: Failed to open database 6 User-defined Exceptions It’s possible to create your type of exceptions. At the moment, only knowing this is more than enough; we won’t put it into practical use any time soon.\n7 Clean-up Actions The try statement has another optional clause that is intended to define clean-up actions that must be executed under all circumstances. For example:\n\u003e\u003e\u003e try: ... raise KeyboardInterrupt ... finally: ... print('Goodbye, world!') ... Goodbye, world! KeyboardInterrupt Traceback (most recent call last): File \"\", line 2, in \u003cmodule\u003e If a finally clause is present, the finally clause will execute as the last task before the try statement completes. The finally clause runs whether or not the try statement produces an exception.\nJust remember, the finally clause will always be executed, no matter if there is an exception or not.\nFor example:\n\u003e\u003e\u003e def bool_return(): ... try: ... return True ... finally: ... return False ... \u003e\u003e\u003e bool_return() False A more complicated example:\n\u003e\u003e\u003e def divide(x, y): ... try: ... result = x / y ... except ZeroDivisionError: ... print(\"division by zero!\") ... else: ... print(\"result is\", result) ... finally: ... print(\"executing finally clause\") ... \u003e\u003e\u003e divide(2, 1) result is 2.0 executing finally clause \u003e\u003e\u003e divide(2, 0) division by zero! executing finally clause \u003e\u003e\u003e divide(\"2\", \"1\") executing finally clause Traceback (most recent call last): File \"\", line 1, in \u003cmodule\u003e File \"\", line 3, in divide TypeError: unsupported operand type(s) for /: 'str' and 'str' As you can see, the finally clause is executed in any event. (The TypeError raised by dividing two strings is not handled by the except clause and therefore re-raised after the finally clause has been executed.)\n8 Predefined Clean-up Actions Some objects define standard clean-up actions to be executed when the object is no longer needed, regardless of whether or not the operation using the object succeeded or failed.\nRead the following example, which tries to open a file and print its contents to the screen:\nfor line in open(\"myfile.txt\"): print(line, end=\"\") The problem with this code is that it leaves the file open for an indeterminate amount of time after this part of the code has finished executing. This is not an issue in simple scripts but can be a problem for larger applications.\nThe with statement allows objects like files to be used in a way that ensures they are always cleaned up promptly and correctly.\nwith open(\"myfile.txt\") as f: for line in f: print(line, end=\"\") After the statement is executed, the file f is always closed, even if a problem was encountered while processing the lines. It’s always a good practice to open a file with the with statement like the example above. If you have forgotten about how to open and read a file, check the previous tutorial.\nSummary Congratulations, because for now, we’ve covered all the basics of Python. Let’s take a quick look at what we’ve learned so far:\ninteractive mode data types: numbers, strings, lists, flow control: while loop, for loop, if/elif/else, etc. functions data types: more about lists: list comprehension, tuple, sequences, stack, queue data types: set, dict, loop through dicts modules input/output, read files handling errors These are more than enough to start working on any small programs.\nIn the following chapters, we will cover:\na little bit about class (which you don’t have to use); using third-party modules to help you achieve what you want; managing different environments (if you are working on multiple projects, this can be useful;) how to learn everything. Please give the previous chapters a quick review before moving on. See you in the next chapter!\n","wordCount":"1662","inLanguage":"en","image":"https://www.guotiexin.com/1200px-Python-logo.png","datePublished":"2022-07-19T00:00:00Z","dateModified":"2022-07-19T00:00:00Z","author":{"@type":"Person","name":"Tiexin Guo | 郭铁心"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://www.guotiexin.com/posts/python-09-error-handling/"},"publisher":{"@type":"Organization","name":"Tiexin Guo","logo":{"@type":"ImageObject","url":"https://www.guotiexin.com/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://www.guotiexin.com accesskey=h title="Tiexin Guo (Alt + H)">Tiexin Guo</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://www.guotiexin.com/about title=About><span>About</span></a></li><li><a href=https://cv.guotiexin.com/ title=CV><span>CV</span>&nbsp;<svg fill="none" shape-rendering="geometricPrecision" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" viewBox="0 0 24 24" height="12" width="12"><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/><path d="M15 3h6v6"/><path d="M10 14 21 3"/></svg></a></li><li><a href=https://www.guotiexin.com/portfolio title=Portfolio><span>Portfolio</span></a></li><li><a href=https://www.guotiexin.com/categories/ title=Categories><span>Categories</span></a></li><li><a href=https://www.guotiexin.com/tags/ title=Tags><span>Tags</span></a></li><li><a href=https://www.guotiexin.com/posts/ title=Archive><span>Archive</span></a></li><li><a href=https://github.com/ironcore864 title><span><i class='fab fa-github fa-fw'></i></span>&nbsp;<svg fill="none" shape-rendering="geometricPrecision" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" viewBox="0 0 24 24" height="12" width="12"><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/><path d="M15 3h6v6"/><path d="M10 14 21 3"/></svg></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><h1 class=post-title>Python Tutorial: 9. Error Handling</h1><div class=post-meta><span title='2022-07-19 00:00:00 +0000 UTC'>July 19, 2022</span>&nbsp;·&nbsp;Tiexin Guo | 郭铁心</div></header><figure class=entry-cover><img loading=lazy srcset="https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo_hu642ccd1f19740d5d9a158214cd86803b_112695_360x0_resize_box_3.png 360w ,https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo_hu642ccd1f19740d5d9a158214cd86803b_112695_480x0_resize_box_3.png 480w ,https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo_hu642ccd1f19740d5d9a158214cd86803b_112695_720x0_resize_box_3.png 720w ,https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo_hu642ccd1f19740d5d9a158214cd86803b_112695_1080x0_resize_box_3.png 1080w ,https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo_hu642ccd1f19740d5d9a158214cd86803b_112695_1500x0_resize_box_3.png 1500w ,https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo.png 3967w" sizes="(min-width: 768px) 720px, 100vw" src=https://www.guotiexin.com/posts/python-09-error-handling/1200px-Python-logo.png alt="Python Tutorial" width=3967 height=1493></figure><div class=post-content><p>We have only slightly mentioned error messages. If you have tried out some of the code examples yourself, I&rsquo;m pretty sure you&rsquo;ve met a few more errors and exceptions. Today, we will go over errors in general.</p><p>There are (at least) two distinguishable kinds of errors:</p><ul><li>syntax errors</li><li>exceptions</li></ul><hr><h2 id=1-syntax-errors>1 Syntax Errors<a hidden class=anchor aria-hidden=true href=#1-syntax-errors>#</a></h2><p>Syntax errors, also known as <em>parsing errors</em>, are caused by incorrect syntax, or <em>grammar</em>.</p><p>They are perhaps the most common kind of complaints you get while you are learning Python:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>while</span> <span class=kc>True</span> <span class=nb>print</span><span class=p>(</span><span class=s1>&#39;Hello world&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span>
</span></span><span class=line><span class=cl>    <span class=k>while</span> <span class=kc>True</span> <span class=nb>print</span><span class=p>(</span><span class=s1>&#39;Hello world&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl>                   <span class=o>^</span>
</span></span><span class=line><span class=cl><span class=ne>SyntaxError</span><span class=p>:</span> <span class=n>invalid</span> <span class=n>syntax</span>
</span></span></code></pre></div><p>The parser repeats the offending line and displays a little &lsquo;arrow&rsquo; pointing at the earliest point in the line where the error was detected.</p><p>The error is caused by (or at least detected at) the token preceding the arrow. In the example above, the error is detected at the function <code>print()</code>, since a colon (<code>:</code>) is missing before it.</p><p>File name and line number are printed so you know where to look in case the input came from a script. It&rsquo;s extremely important to learn to figure out where went wrong and why, because that&rsquo;s all you do when programming.</p><hr><h2 id=2-exceptions>2 Exceptions<a hidden class=anchor aria-hidden=true href=#2-exceptions>#</a></h2><p>Even if a statement or expression is syntactically correct, it may cause an error when an attempt is made to execute it.</p><p><em>Errors detected during execution are called exceptions</em> and are not always &ldquo;fatal&rdquo; in every condition. You will soon learn how to handle exceptions in Python.</p><p>Most exceptions are not handled by programs, however, and result in error messages as shown here:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=mi>1</span><span class=o>/</span><span class=mi>0</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>ZeroDivisionError</span><span class=p>:</span> <span class=n>division</span> <span class=n>by</span> <span class=n>zero</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=mi>4</span> <span class=o>+</span> <span class=n>spam</span><span class=o>*</span><span class=mi>3</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>NameError</span><span class=p>:</span> <span class=n>name</span> <span class=s1>&#39;spam&#39;</span> <span class=ow>is</span> <span class=ow>not</span> <span class=n>defined</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=s1>&#39;2&#39;</span> <span class=o>+</span> <span class=mi>2</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>TypeError</span><span class=p>:</span> <span class=n>can</span> <span class=n>only</span> <span class=n>concatenate</span> <span class=nb>str</span> <span class=p>(</span><span class=ow>not</span> <span class=s2>&#34;int&#34;</span><span class=p>)</span> <span class=n>to</span> <span class=nb>str</span>
</span></span></code></pre></div><p>The last line of the error message indicates what happened.</p><p>Exceptions come in different <em>types</em>, and the type is printed as part of the message.</p><p>The types in the example are ZeroDivisionError, NameError, and TypeError.</p><p>The rest of the line provides detail based on the type of exception and what caused it.</p><hr><h2 id=3-handling-exceptions>3 Handling Exceptions<a hidden class=anchor aria-hidden=true href=#3-handling-exceptions>#</a></h2><p>It is possible to write programs that handle selected exceptions.</p><p>Read the following example, which asks the user for input until a valid integer has been entered, but allows the user to interrupt the program (using Control-C or whatever the operating system supports.)</p><p>Note that a user-generated interruption is signaled by raising the KeyboardInterrupt exception:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>while</span> <span class=kc>True</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=n>x</span> <span class=o>=</span> <span class=nb>int</span><span class=p>(</span><span class=nb>input</span><span class=p>(</span><span class=s2>&#34;Please enter a number: &#34;</span><span class=p>))</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=k>break</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>except</span> <span class=ne>ValueError</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;Oops!  That was no valid number.  Try again...&#34;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span></code></pre></div><p>The try statement works as follows:</p><ul><li>The <code>try</code> clause (the statement(s) between the try and except keywords) is executed.</li><li>If no exception occurs, the except clause is <em>skipped</em> and execution of the try statement are finished.</li><li>If an exception occurs during the execution of the <code>try</code> clause, <em>the rest of the clause is skipped</em>. Then, if the exception&rsquo;s type matches the exception named after the <code>except</code> keyword, the <code>except</code> clause is executed, and <em>then execution continues after the try/except block</em>.</li><li>If an exception occurs that <em>does not match the exception named in the <code>except</code> clause</em>, it is <em>passed on</em> to outer <code>try</code> statements (if there is); if no outer <code>try</code> handler is found, it is an <em>unhandled exception</em>, and execution stops.</li></ul><p>It&rsquo;s worth noting that a <code>try</code> statement may have <em>more than one</em> <code>except</code> clause, to specify handlers for different exceptions. <em>At most one handler will be executed</em>. Handlers only handle exceptions that occur in the corresponding <code>try</code> clause, not in other handlers of the same <code>try</code> statement.</p><p>An <code>except</code> clause may name multiple exceptions as a parenthesized tuple, for example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>...</span> <span class=k>except</span> <span class=p>(</span><span class=ne>RuntimeError</span><span class=p>,</span> <span class=ne>TypeError</span><span class=p>,</span> <span class=ne>NameError</span><span class=p>):</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>pass</span>
</span></span></code></pre></div><p>The <code>try … except</code> statement has an optional <code>else</code> clause, which, when present, must follow all except clauses. It is useful for code that must be executed if the try clause does not raise an exception. For example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>for</span> <span class=n>arg</span> <span class=ow>in</span> <span class=n>sys</span><span class=o>.</span><span class=n>argv</span><span class=p>[</span><span class=mi>1</span><span class=p>:]:</span>
</span></span><span class=line><span class=cl>    <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=n>f</span> <span class=o>=</span> <span class=nb>open</span><span class=p>(</span><span class=n>arg</span><span class=p>,</span> <span class=s1>&#39;r&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=k>except</span> <span class=ne>OSError</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=nb>print</span><span class=p>(</span><span class=s1>&#39;cannot open&#39;</span><span class=p>,</span> <span class=n>arg</span><span class=p>)</span>
</span></span><span class=line><span class=cl>    <span class=k>else</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=nb>print</span><span class=p>(</span><span class=n>arg</span><span class=p>,</span> <span class=s1>&#39;has&#39;</span><span class=p>,</span> <span class=nb>len</span><span class=p>(</span><span class=n>f</span><span class=o>.</span><span class=n>readlines</span><span class=p>()),</span> <span class=s1>&#39;lines&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl>        <span class=n>f</span><span class=o>.</span><span class=n>close</span><span class=p>()</span>
</span></span></code></pre></div><p>The use of the <code>else</code> clause is better than adding additional code to the try clause because it avoids accidentally catching an exception that wasn&rsquo;t raised by the code being protected by the <code>try … except</code> statement.</p><p>Exception handlers don&rsquo;t just handle exceptions if they occur immediately in the try clause, but also if they occur inside functions that are called (even indirectly) in the try clause. For example:</p><pre tabindex=0><code>&gt;&gt;&gt; def this_fails():
...     x = 1/0
...
&gt;&gt;&gt; try:
...     this_fails()
... except ZeroDivisionError as err:
...     print(&#39;Handling run-time error:&#39;, err)
...
Handling run-time error: division by zero
</code></pre><hr><h2 id=4-raising-exceptions>4 Raising Exceptions<a hidden class=anchor aria-hidden=true href=#4-raising-exceptions>#</a></h2><p>The raise statement allows the programmer to force a specified exception to occur. For example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>raise</span> <span class=ne>NameError</span><span class=p>(</span><span class=s1>&#39;HiThere&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>NameError</span><span class=p>:</span> <span class=n>HiThere</span>
</span></span></code></pre></div><p>The sole argument to raise indicates the exception to be raised. This must be either an exception instance or an exception class (a class that derives from Exception). If an exception class is passed, it will be implicitly instantiated by calling its constructor with no arguments:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>raise</span> <span class=ne>ValueError</span>  <span class=c1># shorthand for &#39;raise ValueError()&#39;</span>
</span></span></code></pre></div><p>If you need to determine whether an exception was raised but don&rsquo;t intend to handle it, a simpler form of the raise statement allows you to re-raise the exception:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>raise</span> <span class=ne>NameError</span><span class=p>(</span><span class=s1>&#39;HiThere&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span> <span class=k>except</span> <span class=ne>NameError</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=nb>print</span><span class=p>(</span><span class=s1>&#39;An exception flew by!&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>raise</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=n>An</span> <span class=n>exception</span> <span class=n>flew</span> <span class=n>by</span><span class=err>!</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>2</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>NameError</span><span class=p>:</span> <span class=n>HiThere</span>
</span></span></code></pre></div><hr><h2 id=5-exception-chaining>5 Exception Chaining<a hidden class=anchor aria-hidden=true href=#5-exception-chaining>#</a></h2><p>The raise statement allows an optional form that enables chaining exceptions. Syntax:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=c1># exc must be exception instance or None.</span>
</span></span><span class=line><span class=cl><span class=k>raise</span> <span class=ne>RuntimeError</span> <span class=kn>from</span> <span class=nn>exc</span>
</span></span></code></pre></div><p>This can be useful when you are transforming exceptions. Example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>def</span> <span class=nf>func</span><span class=p>():</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>raise</span> <span class=ne>ConnectionError</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=n>func</span><span class=p>()</span>
</span></span><span class=line><span class=cl><span class=o>...</span> <span class=k>except</span> <span class=ne>ConnectionError</span> <span class=k>as</span> <span class=n>exc</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>raise</span> <span class=ne>RuntimeError</span><span class=p>(</span><span class=s1>&#39;Failed to open database&#39;</span><span class=p>)</span> <span class=kn>from</span> <span class=nn>exc</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>2</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>2</span><span class=p>,</span> <span class=ow>in</span> <span class=n>func</span>
</span></span><span class=line><span class=cl><span class=ne>ConnectionError</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=n>The</span> <span class=n>above</span> <span class=n>exception</span> <span class=n>was</span> <span class=n>the</span> <span class=n>direct</span> <span class=n>cause</span> <span class=n>of</span> <span class=n>the</span> <span class=n>following</span> <span class=n>exception</span><span class=p>:</span>
</span></span><span class=line><span class=cl>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>4</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl><span class=ne>RuntimeError</span><span class=p>:</span> <span class=n>Failed</span> <span class=n>to</span> <span class=nb>open</span> <span class=n>database</span>
</span></span></code></pre></div><hr><h2 id=6-user-defined-exceptions>6 User-defined Exceptions<a hidden class=anchor aria-hidden=true href=#6-user-defined-exceptions>#</a></h2><p>It&rsquo;s possible to create your type of exceptions. At the moment, only knowing this is more than enough; we won&rsquo;t put it into practical use any time soon.</p><hr><h2 id=7-clean-up-actions>7 Clean-up Actions<a hidden class=anchor aria-hidden=true href=#7-clean-up-actions>#</a></h2><p>The <code>try</code> statement has another optional clause that is intended to define <em>clean-up actions</em> that <em>must be executed under all circumstances</em>. For example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>raise</span> <span class=ne>KeyboardInterrupt</span>
</span></span><span class=line><span class=cl><span class=o>...</span> <span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=nb>print</span><span class=p>(</span><span class=s1>&#39;Goodbye, world!&#39;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=n>Goodbye</span><span class=p>,</span> <span class=n>world</span><span class=err>!</span>
</span></span><span class=line><span class=cl><span class=ne>KeyboardInterrupt</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>2</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span></code></pre></div><p>If a <code>finally</code> clause is present, the <code>finally</code> clause will execute as the last task before the try statement completes. The <code>finally</code> clause runs whether or not the try statement produces an exception.</p><p>Just remember, the <code>finally</code> clause will always be executed, no matter if there is an exception or not.</p><p>For example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>def</span> <span class=nf>bool_return</span><span class=p>():</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=k>return</span> <span class=kc>True</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=k>return</span> <span class=kc>False</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=n>bool_return</span><span class=p>()</span>
</span></span><span class=line><span class=cl><span class=kc>False</span>
</span></span></code></pre></div><p>A more complicated example:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=k>def</span> <span class=nf>divide</span><span class=p>(</span><span class=n>x</span><span class=p>,</span> <span class=n>y</span><span class=p>):</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>try</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=n>result</span> <span class=o>=</span> <span class=n>x</span> <span class=o>/</span> <span class=n>y</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>except</span> <span class=ne>ZeroDivisionError</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;division by zero!&#34;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>else</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;result is&#34;</span><span class=p>,</span> <span class=n>result</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>     <span class=k>finally</span><span class=p>:</span>
</span></span><span class=line><span class=cl><span class=o>...</span>         <span class=nb>print</span><span class=p>(</span><span class=s2>&#34;executing finally clause&#34;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=o>...</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=n>divide</span><span class=p>(</span><span class=mi>2</span><span class=p>,</span> <span class=mi>1</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=n>result</span> <span class=ow>is</span> <span class=mf>2.0</span>
</span></span><span class=line><span class=cl><span class=n>executing</span> <span class=k>finally</span> <span class=n>clause</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=n>divide</span><span class=p>(</span><span class=mi>2</span><span class=p>,</span> <span class=mi>0</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=n>division</span> <span class=n>by</span> <span class=n>zero</span><span class=err>!</span>
</span></span><span class=line><span class=cl><span class=n>executing</span> <span class=k>finally</span> <span class=n>clause</span>
</span></span><span class=line><span class=cl><span class=o>&gt;&gt;&gt;</span> <span class=n>divide</span><span class=p>(</span><span class=s2>&#34;2&#34;</span><span class=p>,</span> <span class=s2>&#34;1&#34;</span><span class=p>)</span>
</span></span><span class=line><span class=cl><span class=n>executing</span> <span class=k>finally</span> <span class=n>clause</span>
</span></span><span class=line><span class=cl><span class=n>Traceback</span> <span class=p>(</span><span class=n>most</span> <span class=n>recent</span> <span class=n>call</span> <span class=n>last</span><span class=p>):</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>1</span><span class=p>,</span> <span class=ow>in</span> <span class=o>&lt;</span><span class=n>module</span><span class=o>&gt;</span>
</span></span><span class=line><span class=cl>  <span class=n>File</span> <span class=s2>&#34;&lt;stdin&gt;&#34;</span><span class=p>,</span> <span class=n>line</span> <span class=mi>3</span><span class=p>,</span> <span class=ow>in</span> <span class=n>divide</span>
</span></span><span class=line><span class=cl><span class=ne>TypeError</span><span class=p>:</span> <span class=n>unsupported</span> <span class=n>operand</span> <span class=nb>type</span><span class=p>(</span><span class=n>s</span><span class=p>)</span> <span class=k>for</span> <span class=o>/</span><span class=p>:</span> <span class=s1>&#39;str&#39;</span> <span class=ow>and</span> <span class=s1>&#39;str&#39;</span>
</span></span></code></pre></div><p>As you can see, the <code>finally</code> clause is executed in any event. (The TypeError raised by dividing two strings is not handled by the except clause and therefore re-raised after the <code>finally</code> clause has been executed.)</p><hr><h2 id=8-predefined-clean-up-actions>8 Predefined Clean-up Actions<a hidden class=anchor aria-hidden=true href=#8-predefined-clean-up-actions>#</a></h2><p>Some objects define standard clean-up actions to be executed when the object is no longer needed, regardless of whether or not the operation using the object succeeded or failed.</p><p>Read the following example, which tries to open a file and print its contents to the screen:</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>for</span> <span class=n>line</span> <span class=ow>in</span> <span class=nb>open</span><span class=p>(</span><span class=s2>&#34;myfile.txt&#34;</span><span class=p>):</span>
</span></span><span class=line><span class=cl>    <span class=nb>print</span><span class=p>(</span><span class=n>line</span><span class=p>,</span> <span class=n>end</span><span class=o>=</span><span class=s2>&#34;&#34;</span><span class=p>)</span>
</span></span></code></pre></div><p>The problem with this code is that it leaves the file open for an indeterminate amount of time after this part of the code has finished executing. This is not an issue in simple scripts but can be a problem for larger applications.</p><p>The <code>with</code> statement allows objects like files to be used in a way that ensures they are always cleaned up promptly and correctly.</p><div class=highlight><pre tabindex=0 class=chroma><code class=language-python data-lang=python><span class=line><span class=cl><span class=k>with</span> <span class=nb>open</span><span class=p>(</span><span class=s2>&#34;myfile.txt&#34;</span><span class=p>)</span> <span class=k>as</span> <span class=n>f</span><span class=p>:</span>
</span></span><span class=line><span class=cl>    <span class=k>for</span> <span class=n>line</span> <span class=ow>in</span> <span class=n>f</span><span class=p>:</span>
</span></span><span class=line><span class=cl>        <span class=nb>print</span><span class=p>(</span><span class=n>line</span><span class=p>,</span> <span class=n>end</span><span class=o>=</span><span class=s2>&#34;&#34;</span><span class=p>)</span>
</span></span></code></pre></div><p>After the statement is executed, the file <code>f</code> is always closed, even if a problem was encountered while processing the lines. It&rsquo;s always a good practice to open a file with the <code>with</code> statement like the example above. If you have forgotten about how to open and read a file, check the <a href=../python-08-input-output/>previous tutorial</a>.</p><hr><h2 id=summary>Summary<a hidden class=anchor aria-hidden=true href=#summary>#</a></h2><p>Congratulations, because for now, we&rsquo;ve covered all the basics of Python. Let&rsquo;s take a quick look at what we&rsquo;ve learned so far:</p><ul><li>interactive mode</li><li>data types: numbers, strings, lists,</li><li>flow control: while loop, for loop, if/elif/else, etc.</li><li>functions</li><li>data types: more about lists: list comprehension, tuple, sequences, stack, queue</li><li>data types: set, dict, loop through dicts</li><li>modules</li><li>input/output, read files</li><li>handling errors</li></ul><p>These are more than enough to start working on any small programs.</p><p>In the following chapters, we will cover:</p><ul><li>a little bit about class (which you don&rsquo;t have to use);</li><li>using third-party modules to help you achieve what you want;</li><li>managing different environments (if you are working on multiple projects, this can be useful;)</li><li>how to learn everything.</li></ul><p>Please give the previous chapters a quick review before moving on. See you in the next chapter!</p></div><footer class=post-footer><ul class=post-tags><li><a href=https://www.guotiexin.com/tags/python/>python</a></li></ul></footer></article></main><footer class=footer><span>&copy; 2022 <a href=https://www.guotiexin.com>Tiexin Guo</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>